---
title: "mixedAgent"
author: "Thomas Cleary"
date: "20/10/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo=FALSE}
# Reset the Rstudio environment
reset_env <- function() {
  # clear the global namespace
  rm(list=setdiff(ls(envir = .GlobalEnv), "reset_env"), envir = .GlobalEnv)

  # un-attach loaded packages
  if (!is.null(sessionInfo()$otherPkgs)) {
    invisible(
      lapply(paste0('package:', names(sessionInfo()$otherPkgs)),
             detach, character.only=TRUE, unload=TRUE)
    )
  }

  # stop R converting strings to factors automatically
  options(stringsAsFactors = FALSE)

  library(ggplot2)
  library(patchwork)
}
```

```{r, echo=FALSE, message=FALSE, results='hide', error=FALSE, warning=FALSE}
reset_env()
```

```{r}
mixed.spy = read.csv(paste0("../mixed-spy.csv"))
mixed.res = read.csv(paste0("../mixed-resistance.csv"))
mixed.overall = read.csv(paste0("../mixed-overall.csv"))
```


# Plot spy performance
```{r}
last_mixed_row = mixed.spy[dim(mixed.spy)[1],]

max_sims = last_mixed_row$games_played[1]

basic_spy_converged = data.frame(
  games_played = seq(1:max_sims),
  spy_win_ratio = rep(0.70, max_sims)
)
last_basic_converged_row = basic_spy_converged[dim(basic_spy_converged)[1],]

random_spy_converged = data.frame(
  games_played = seq(1:max_sims),
  spy_win_ratio = rep(0.54, max_sims)
)
last_random_converged_row = random_spy_converged[dim(random_spy_converged)[1],]

basicMCTS_spy_converged = data.frame(
  games_played = seq(1:max_sims),
  spy_win_ratio = rep(0.72, max_sims)
)
last_basicMCTS_converged_row = basicMCTS_spy_converged[dim(basicMCTS_spy_converged)[1],]

randomMCTS_spy_converged = data.frame(
  games_played = seq(1:max_sims),
  spy_win_ratio = rep(0.73, max_sims)
)
last_randomMCTS_converged_row = randomMCTS_spy_converged[dim(randomMCTS_spy_converged)[1],]
```

```{r}
spy_plot = ggplot() +
  # horizontal lines
  geom_line(
    data = basic_spy_converged, aes(x = games_played, y = spy_win_ratio, colour = "Basic Agent")
  ) +
  # geom_point(
  #   data = last_basic_converged_row, aes(x = games_played, y = spy_win_ratio, colour = "Basic Agent")
  # ) +
  # geom_text(
  #   data=last_basic_converged_row, 
  #   size=3.5,
  #   aes(
  #     x=games_played, y = spy_win_ratio, 
  #     label = paste0(round(spy_win_ratio, 2) * 100, "%"),
  #     colour="Basic Agent",
  #     ),
  #     vjust = -0.5,
  #   show.legend = FALSE
  # ) + 
  
  
  geom_line(
    data = random_spy_converged, aes(x = games_played, y = spy_win_ratio, colour = "Random Agent")
  ) +
  # geom_point(
  #   data = last_random_converged_row, aes(x = games_played, y = spy_win_ratio, colour = "Random Agent")
  # ) +
  # geom_text(
  #   data=last_random_converged_row, 
  #   size=3.5,
  #   aes(
  #     x=games_played, y = spy_win_ratio, 
  #     label = paste0(round(spy_win_ratio, 2) * 100, "%"),
  #     colour="Random Agent",
  #     ),
  #     vjust = -0.5,
  #   show.legend = FALSE
  # ) +
  
    # converged simple agent values first
  geom_line(
    data = basicMCTS_spy_converged, aes(x = games_played, y = spy_win_ratio, colour = "BasicMCTS Agent")
  ) +
  # geom_point(
  #   data = last_basicMCTS_converged_row, aes(x = games_played, y = spy_win_ratio, colour = "BasicMCTS Agent")
  # ) +
  # geom_text(
  #   data=last_basicMCTS_converged_row, 
  #   size=3.5,
  #   aes(
  #     x=games_played, y = spy_win_ratio, 
  #     label = paste0(round(spy_win_ratio, 2) * 100, "%"),
  #     colour="BasicMCTS Agent",
  #     ),
  #     vjust = -0.5,
  #   show.legend = FALSE
  # ) + 
  
  
  geom_line(
    data = randomMCTS_spy_converged, aes(x = games_played, y = spy_win_ratio, colour = "RandomMCTS Agent")
  ) +
  # geom_point(
  #   data = last_randomMCTS_converged_row, aes(x = games_played, y = spy_win_ratio, colour = "RandomMCTS Agent")
  # ) +
  # geom_text(
  #   data=last_randomMCTS_converged_row, 
  #   size=3.5,
  #   aes(
  #     x=games_played, y = spy_win_ratio, 
  #     label = paste0(round(spy_win_ratio, 2) * 100, "%"),
  #     colour="RandomMCTS Agent",
  #     ),
  #     vjust = -0.5,
  #   show.legend = FALSE
  # ) +
  
  
  # MIXED AGENT
  geom_line(
    data = mixed.spy, aes(x = games_played, y = spy_win_ratio, colour = "Mixed Agent")
  ) +
  geom_point(
    data = last_mixed_row, aes(x = games_played, y = spy_win_ratio, colour = "Mixed Agent")
  ) +
  geom_text(
    data=last_mixed_row, 
    size=3.5,
    aes(
      x=games_played, y = spy_win_ratio, 
      label = paste0(round(spy_win_ratio, 2) * 100, "%"),
      colour="Mixed Agent",
      ),
      vjust = -0.5,
    show.legend = FALSE
  ) + 
  
  ylim(0, 1) + 
  
  scale_x_continuous(
    breaks=seq(0, last_mixed_row$games_played, 100),
    labels = scales::comma
  ) + 
  
  labs(
    subtitle = "Games Played as Spy",
    x = "",
    y = "",
    colour = ""
  ) + 
  
  theme(
    axis.text.x = element_text(angle = 90)
  )



print(spy_plot)
```

# Plot res performance
```{r}
last_mixed_row = mixed.res[dim(mixed.res)[1],]

max_sims = last_mixed_row$games_played[1]

basic_res_converged = data.frame(
  games_played = seq(1:max_sims),
  res_win_ratio = rep(0.46, max_sims)
)
last_basic_converged_row = basic_res_converged[dim(basic_res_converged)[1],]

random_res_converged = data.frame(
  games_played = seq(1:max_sims),
  res_win_ratio = rep(0.45, max_sims)
)
last_random_converged_row = random_res_converged[dim(random_res_converged)[1],]

basicMCTS_res_converged = data.frame(
  games_played = seq(1:max_sims),
  res_win_ratio = rep(0.25, max_sims)
)
last_basicMCTS_converged_row = basicMCTS_res_converged[dim(basicMCTS_res_converged)[1],]

randomMCTS_res_converged = data.frame(
  games_played = seq(1:max_sims),
  res_win_ratio = rep(0.24, max_sims)
)
last_randomMCTS_converged_row = randomMCTS_res_converged[dim(randomMCTS_res_converged)[1],]
```

```{r}
res_plot = ggplot() +
  # horizontal lines
  geom_line(
    data = basic_res_converged, aes(x = games_played, y = res_win_ratio, colour = "Basic Agent")
  ) +
  # geom_point(
  #   data = last_basic_converged_row, aes(x = games_played, y = res_win_ratio, colour = "Basic Agent")
  # ) +
  # geom_text(
  #   data=last_basic_converged_row, 
  #   size=3.5,
  #   aes(
  #     x=games_played, y = res_win_ratio, 
  #     label = paste0(round(res_win_ratio, 2) * 100, "%"),
  #     colour="Basic Agent",
  #     ),
  #     vjust = -0.5,
  #   show.legend = FALSE
  # ) + 
  
  
  geom_line(
    data = random_res_converged, aes(x = games_played, y = res_win_ratio, colour = "Random Agent")
  ) +
  # geom_point(
  #   data = last_random_converged_row, aes(x = games_played, y = res_win_ratio, colour = "Random Agent")
  # ) +
  # geom_text(
  #   data=last_random_converged_row, 
  #   size=3.5,
  #   aes(
  #     x=games_played, y = res_win_ratio, 
  #     label = paste0(round(res_win_ratio, 2) * 100, "%"),
  #     colour="Random Agent",
  #     ),
  #     vjust = -0.5,
  #   show.legend = FALSE
  # ) +
  
    # converged simple agent values first
  geom_line(
    data = basicMCTS_res_converged, aes(x = games_played, y = res_win_ratio, colour = "BasicMCTS Agent")
  ) +
  # geom_point(
  #   data = last_basicMCTS_converged_row, aes(x = games_played, y = res_win_ratio, colour = "BasicMCTS Agent")
  # ) +
  # geom_text(
  #   data=last_basicMCTS_converged_row, 
  #   size=3.5,
  #   aes(
  #     x=games_played, y = res_win_ratio, 
  #     label = paste0(round(res_win_ratio, 2) * 100, "%"),
  #     colour="BasicMCTS Agent",
  #     ),
  #     vjust = -0.5,
  #   show.legend = FALSE
  # ) + 
  
  
  geom_line(
    data = randomMCTS_res_converged, aes(x = games_played, y = res_win_ratio, colour = "RandomMCTS Agent")
  ) +
  # geom_point(
  #   data = last_randomMCTS_converged_row, aes(x = games_played, y = res_win_ratio, colour = "RandomMCTS Agent")
  # ) +
  # geom_text(
  #   data=last_randomMCTS_converged_row, 
  #   size=3.5,
  #   aes(
  #     x=games_played, y = res_win_ratio, 
  #     label = paste0(round(res_win_ratio, 2) * 100, "%"),
  #     colour="RandomMCTS Agent",
  #     ),
  #     vjust = -0.5,
  #   show.legend = FALSE
  # ) +
  
  
  # MIXED AGENT
  geom_line(
    data = mixed.res, aes(x = games_played, y = res_win_ratio, colour = "Mixed Agent")
  ) +
  geom_point(
    data = last_mixed_row, aes(x = games_played, y = res_win_ratio, colour = "Mixed Agent")
  ) +
  geom_text(
    data=last_mixed_row, 
    size=3.5,
    aes(
      x=games_played, y = res_win_ratio, 
      label = paste0(round(res_win_ratio, 2) * 100, "%"),
      colour="Mixed Agent",
      ),
      vjust = -0.5,
    show.legend = FALSE
  ) + 
  
  ylim(0, 1) + 
  
  scale_x_continuous(
    breaks=seq(0, last_mixed_row$games_played, 100),
    labels = scales::comma
  ) + 
  
  labs(
    subtitle = "Games Played as Resistance",
    x = "",
    y = "",
    colour = ""
  ) + 
  
  theme(
    axis.text.x = element_text(angle = 90)
  )



print(res_plot)
```


# Plot overall performance
```{r}
last_mixed_row = mixed.overall[dim(mixed.overall)[1],]

max_sims = last_mixed_row$games_played[1]

basic_overall_converged = data.frame(
  games_played = seq(1:max_sims),
  win_ratio = rep(0.55, max_sims)
)
last_basic_converged_row = basic_overall_converged[dim(basic_overall_converged)[1],]

random_overall_converged = data.frame(
  games_played = seq(1:max_sims),
  win_ratio = rep(0.49, max_sims)
)
last_random_converged_row = random_overall_converged[dim(random_overall_converged)[1],]

basicMCTS_overall_converged = data.frame(
  games_played = seq(1:max_sims),
  win_ratio = rep(0.45, max_sims)
)
last_basicMCTS_converged_row = basicMCTS_overall_converged[dim(basicMCTS_overall_converged)[1],]

randomMCTS_overall_converged = data.frame(
  games_played = seq(1:max_sims),
  win_ratio = rep(0.44, max_sims)
)
last_randomMCTS_converged_row = randomMCTS_overall_converged[dim(randomMCTS_overall_converged)[1],]
```

```{r}
overall_plot = ggplot() +
  # horizontal lines
  geom_line(
    data = basic_overall_converged, aes(x = games_played, y = win_ratio, colour = "Basic Agent")
  ) +
  # geom_point(
  #   data = last_basic_converged_row, aes(x = games_played, y = win_ratio, colour = "Basic Agent")
  # ) +
  # geom_text(
  #   data=last_basic_converged_row, 
  #   size=3.5,
  #   aes(
  #     x=games_played, y = win_ratio, 
  #     label = paste0(round(win_ratio, 2) * 100, "%"),
  #     colour="Basic Agent",
  #     ),
  #     vjust = -0.5,
  #   show.legend = FALSE
  # ) + 
  
  
  geom_line(
    data = random_overall_converged, aes(x = games_played, y = win_ratio, colour = "Random Agent")
  ) +
  # geom_point(
  #   data = last_random_converged_row, aes(x = games_played, y = win_ratio, colour = "Random Agent")
  # ) +
  # geom_text(
  #   data=last_random_converged_row, 
  #   size=3.5,
  #   aes(
  #     x=games_played, y = win_ratio, 
  #     label = paste0(round(win_ratio, 2) * 100, "%"),
  #     colour="Random Agent",
  #     ),
  #     vjust = -0.5,
  #   show.legend = FALSE
  # ) +
  
    # converged simple agent values first
  geom_line(
    data = basicMCTS_overall_converged, aes(x = games_played, y = win_ratio, colour = "BasicMCTS Agent")
  ) +
  # geom_point(
  #   data = last_basicMCTS_converged_row, aes(x = games_played, y = win_ratio, colour = "BasicMCTS Agent")
  # ) +
  # geom_text(
  #   data=last_basicMCTS_converged_row, 
  #   size=3.5,
  #   aes(
  #     x=games_played, y = win_ratio, 
  #     label = paste0(round(win_ratio, 2) * 100, "%"),
  #     colour="BasicMCTS Agent",
  #     ),
  #     vjust = -0.5,
  #   show.legend = FALSE
  # ) + 
  
  
  geom_line(
    data = randomMCTS_overall_converged, aes(x = games_played, y = win_ratio, colour = "RandomMCTS Agent")
  ) +
  # geom_point(
  #   data = last_randomMCTS_converged_row, aes(x = games_played, y = win_ratio, colour = "RandomMCTS Agent")
  # ) +
  # geom_text(
  #   data=last_randomMCTS_converged_row, 
  #   size=3.5,
  #   aes(
  #     x=games_played, y = win_ratio, 
  #     label = paste0(round(win_ratio, 2) * 100, "%"),
  #     colour="RandomMCTS Agent",
  #     ),
  #     vjust = -0.5,
  #   show.legend = FALSE
  # ) +
  
  
  # MIXED AGENT
  geom_line(
    data = mixed.overall, aes(x = games_played, y = win_ratio, colour = "Mixed Agent")
  ) +
  geom_point(
    data = last_mixed_row, aes(x = games_played, y = win_ratio, colour = "Mixed Agent")
  ) +
  geom_text(
    data=last_mixed_row, 
    size=3.5,
    aes(
      x=games_played, y = win_ratio, 
      label = paste0(round(win_ratio, 2) * 100, "%"),
      colour="Mixed Agent",
      ),
      vjust = -0.5,
    show.legend = FALSE
  ) + 
  
  ylim(0, 1) + 
  
  scale_x_continuous(
    breaks=seq(0, last_mixed_row$games_played, 100),
    labels = scales::comma
  ) + 
  
  labs(
    subtitle = "All Games Played",
    x = "",
    y = "",
    colour = ""
  ) + 
  
  theme(
    axis.text.x = element_text(angle = 90)
  )



print(overall_plot)
```

# all plots
``` {r, fig.height=3, fig.width=6}
library(ggpubr)

all.plots = ggarrange(
  spy_plot, res_plot, overall_plot,
  ncol=3, nrow=1, common.legend=TRUE,
  legend="top"
)


all.plots = annotate_figure(
  all.plots,
  top = text_grob("Win Ratio of Mixed Agents with 'Random Agent' Opponents",
                  size=18, face="bold"),
  left = text_grob("Win Ratio", size=14, rot=90),
  bottom = text_grob("Games Simulated", size=14)
)

print(all.plots)
```